<?php
declare(strict_types=1);
namespace App\Domain\Governance\Enums;
enum DrmReasonCode: string {
 case HEARTBEAT_48H_FAIL='HEARTBEAT_48H_FAIL';
 case FINGERPRINT_MISMATCH='FINGERPRINT_MISMATCH';
 case MANUAL_QUARANTINE='MANUAL_QUARANTINE';
 case DISARM_SUCCESS='DISARM_SUCCESS';
 case DISARM_FAIL='DISARM_FAIL';
 case ANNIHILATE_CONFIRMED='ANNIHILATE_CONFIRMED';
}
